name: Docker image Check

on:
  push:
    branches: ["Develop"]
  workflow_dispatch:
  
  jobs:
    Docker-Check:
      runs-on: ubuntu-latest
      permissions: 
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Log in to Docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCER_USERNAME}}
            password: ${{ secrets.DOCER_PASSWORD}}